# Generated by Django 2.1.10 on 2020-03-05 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('file_url', models.URLField(help_text='文件url', verbose_name='文件url')),
                ('file_name', models.CharField(help_text='文件名', max_length=48, verbose_name='文件名')),
                ('title', models.CharField(help_text='文件标题', max_length=150, verbose_name='文件标题')),
                ('desc', models.TextField(help_text='文件描述', verbose_name='文件描述')),
                ('image_url', models.URLField(default='', help_text='封面图片url', verbose_name='封面图片url')),
            ],
            options={
                'verbose_name': '文件表',
                'verbose_name_plural': '文件表',
                'db_table': 'tb_docs',
            },
        ),
    ]
