# Generated by Django 2.1.10 on 2020-03-06 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '用户个人信息', 'verbose_name_plural': '用户个人信息'},
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='tb_users_profile',
        ),
    ]
